### ISSUE TITLE
file gooddisriminator.h5 is not found

### ISSUE THREAD

**Issue by ankitpetkar** [llSourcell/how_to_generate_video#1]

**Comment by san7988** [comment]
You can get the trained model files from [here](https://github.com/platers/Logograms-GAN)
However, there are some dimension discrepancy between the trained generator and the generator_model in the code which I could not resolve.
***********************************************************
Traceback (most recent call last):
  File "video_generator.py", line 201, in <module>
    generate(1)
  File "video_generator.py", line 147, in generate
    generator.load_weights('goodgenerator.h5')
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/keras/engine/topology.py", line 2500, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/keras/engine/topology.py", line 2585, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 990, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 501, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2319, in create_op
    set_shapes_for_outputs(ret)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1711, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 210, in _AssignShape
    return [op.inputs[0].get_shape().merge_with(op.inputs[1].get_shape())]
  File "/home/sanjeev/anaconda3/envs/automation/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 570, in merge_with
    (self, other))
**ValueError: Shapes (5, 5, 8, 64) and (64, 128, 5, 5) are not compatible**

**Comment by hutauf** [comment]
I get this error if I try to train the model ( "train(400, 10, True)" )
ValueError: Negative dimension size caused by subtracting 4 from 1 for 'average_pooling2d_2/AvgPool' (op: 'AvgPool') with input shapes: [?,1,128,64].

Seems to be a related problem.

**Comment by xkortex** [comment]
Third'd. I was able to avoid the FileNotFound by running train() first, but then I hit the ValueError in the 2D pooling.

**Comment by xkortex** [comment]
The issue stems from Keras image ordering. The notebook is using Theano notation, you probably have your config set to TF notation. You can patch this by adding this to the top of your code:

```
from keras import backend as K
K.set_image_dim_ordering('th')
```

**Comment by hutauf** [comment]
I fixed it by changing the shape order from feature, width ,height to width, height, feature. Yes, I'm using TF.

**Comment by xkortex** [comment]
Anyone else getting ` OSError: Unable to open file (File signature not found)` ?

Seems to be an issue that occurs when the hdf5 file is closed improperly. I'm pulling directly from the platers repo. 

Also, there are still absolute paths in the code: 
`                    "D:\ML\keras-dcgan-master\logo-generated-images\\"+str(epoch)+"_"+str(index)+".png")
`
Tsk tsk!!

**Comment by hutauf** [comment]
I am getting this:
OSError: Unable to create file (Unable to truncate a file which is already open)
Looks similar. Saving the generator weights works fine, only the discriminator fails.

**Comment by xkortex** [comment]
I created a [pull request](https://github.com/llSourcell/how_to_generate_video/pull/2) which fixes most of these issues. If you don't wanna wait for it to get merged you can [pull my repo or look at the changes I made](https://github.com/xkortex/how_to_generate_video).

**Comment by vikashtitan** [comment]
OSError: Unable to open file (Unable to open file: name = 'goodgenerator.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
Please suggest..
